# Generated by Django 5.1 on 2024-08-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Appartment', 'Appartment'), ('Hostel', 'Hostel'), ('House', 'House')], default='Appartment', max_length=20)),
                ('age', models.IntegerField(default=0, max_length=2)),
            ],
        ),
    ]
