# Generated by Django 5.1 on 2024-08-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
