# Generated by Django 5.1 on 2024-08-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
